# Generated by Django 4.0.2 on 2022-05-12 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminlogin',
            old_name='user_name',
            new_name='username',
        ),
    ]
