# Generated by Django 4.0.2 on 2022-05-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'user_art',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('message', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'contact_us',
            },
        ),
    ]
