# Generated by Django 4.0.2 on 2022-05-29 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0002_product'),
        ('user_app', '0002_contactus_contact_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.artuser')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
