# Generated by Django 4.0.2 on 2022-05-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(upload_to='product/')),
            ],
            options={
                'db_table': 'add_product',
            },
        ),
    ]
